export const UPDATE_AGASU_NAZHIGAI="UPDATE_AGASU_NAZHIGAI";
export const UPDATE_AGASU_VINADI="UPDATE_AGASU_VINADI";

export const UPDATE_NAME = "UPDATE_NAME";

export const UPDATE_SUN_HOUR = "UPDATE_SUN_HOUR";
export const UPDATE_SUN_MINUTE="UPDATE_SUN_MINUTE";

export const BIRTH_HOUR="BIRTH_HOUR";
export const BIRTH_MINUTES="BIRTH_MINUTES";

export const UPDATE_GENDER = "UPDATE_GENDER";

export const UPDATE_DAY = "UPDATE_DAY";

export const UPDATE_JANANA_VINADI = "UPDATE_JANANA_VINADI"
export const UPDATE_JANANA_NAZIGAI = "UPDATE_JANANA_NAZIGAI"

export const UPDATE_KULIGAN = "UPDATE_KULIGAN"

export const LAKNAM_IRUPU = "LAKNAM_IRUPU";
export const LAKNAM_SEL = "LAKNAM_SEL";
export const UPDATE_LUKNAM = "UPDATE_LUKNAM"; 

export const NATCH = "NATCH";
export const NATIRUPU  = "NATIRUPU";
export const NATSEL = "NATSEL"; 
export const AADHI = "AADHI";